### PR TITLE
Updated the link on the GO TO CHAT button that was not working previo…

### LINKED ISSUE #3: link not working
**Description**
the link will not work anymore please do replace this link.

**To Reproduce**
1. Go to the link
2. it wont work.

**Expected behavior**
to go to the chat website

**Screenshots**
Screenshot 2024-09-28 131751

**Desktop (please complete the following information):**
 - OS: widnows
 - Browser firefox
 - Version 130.0

### PR DESCRIPTION
**Pull request by prateekbisht23**
Fixes #3

I have changed the previously not working link on the "GO TO CHAT" button to the chat.html path that opent the chat interface.

Uploading Screen Recording 2024-09-29 at 11.59.37 AM.mov…

### CODE REVIEW

**Comment by Dahsle** [comment]
Hello, thanks for your input. I am not an experienced programmer. This is my hobby. The site is currently live. It works at https://dahsle.netlify.app/ until the main domain is updated.

**Comment by prateekbisht23** [comment]
But the "Go To Chat" button doesn't work it shows an error - for you i have also attached a video.

https://github.com/user-attachments/assets/c8dfbce8-9ee2-43c4-b7c6-d52715339439

I have tried to fix the issue in the pull request,
You can review the code and test it yourself and accept if satisfied!!

Or maybe its an issue with the link your sharing!!
Because this deploy link works perfectly - 

https://deploy-preview-4--dahsle.netlify.app/

**Comment by Dahsle** [comment]
Looks great as I wanted the button adaptive site was on a subdomain I transferred to the domain but DNS is still pending

**Comment by Dahsle** [comment]
It's been almost a day, they should connect DNS

**Comment by prateekbisht23** [comment]
Okay!! now i get get it, It was the problem of the pending dns of the subdomain!!

**Comment by prateekbisht23** [comment]
The issue has resolved after merging!!

**Pull request merged**
